language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - python3
      - python3-pip

before_install:
  - source $TRAVIS_BUILD_DIR/install.sh

script:
  - $TRAVIS_BUILD_DIR/install.sh build_platform nrf52840
  - $TRAVIS_BUILD_DIR/install.sh build_platform esp32
  - $TRAVIS_BUILD_DIR/install.sh build_platform uno
  - $TRAVIS_BUILD_DIR/install.sh build_platform leonardo
  - $TRAVIS_BUILD_DIR/install.sh build_platform zero
  - $TRAVIS_BUILD_DIR/install.sh build_platform esp8266
  - $TRAVIS_BUILD_DIR/install.sh build_platform m4

notifications:
  email:
    on_success: change
    on_failure: change
