language: c
sudo: false

git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

before_install:
  - pip3 install clint

script:
  - python3 build_platform.py uno leonardo mega2560 zero esp8266 esp32


notifications:
  email:
    on_success: change
    on_failure: change
