language: c
sudo: false

git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

before_install:
  - pip3 install clint
  - python3 $TRAVIS_BUILD_DIR/arduino_install.py

script:
  - python3 build_platform.py uno


notifications:
  email:
    on_success: change
    on_failure: change
