language: c
sudo: false

git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - python3
      - python3-pip

before_install:
  - pip3 install clint
  - python3 $TRAVIS_BUILD_DIR/arduino_install.py

script:
  - build_platform nrf52840
  - build_platform esp32
  - build_platform uno
  - build_platform leonardo
  - build_platform zero
  - build_platform esp8266
  - build_platform m4

notifications:
  email:
    on_success: change
    on_failure: change
