name: Github Arduino Library CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: pre-install
      run: |
        source install.sh
    - name: install libraries
      run: |
        arduino --install-library "Adafruit BusIO"
    - name: test platform
      run: |
        build_platform esp32
        build_platform uno
        build_platform leonardo
        build_platform zero
        build_platform esp8266
        build_platform m4
        build_platform nrf52840

