name: Github Arduino Library CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: pre-install
      run: |
        source install.sh
    - name: test platform
      run: |
        ./build.sh build_platform esp32
        ./build.sh build_platform uno
        ./build.sh build_platform leonardo
        ./build.sh build_platform zero
        ./build.sh build_platform esp8266
        ./build.sh build_platform m4
        ./build.sh build_platform nrf52840

